set_property SRC_FILE_INFO {cfile:C:/Users/ozair/Documents/Github/DMA/project_1/project_1.srcs/constrs_1/new/normal.xdc rfile:../../../project_1.srcs/constrs_1/new/normal.xdc id:1 order:EARLY} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports sys_clk_clk_p]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports sys_clk_clk_n]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G3 [get_ports LED_A1]
